export * from './DashboardPage';
export * from './HaircutPage';
export * from './MakeupPage';
export * from './ManicurePage';
export * from './MassagePage'
export * from './NotificationPage'
export * from './NearbyLocationPage'
export * from './ProfilePage'
export * from './InboxPage'
export * from './MyBookingPage'
export * from './ExplorePage'
export * from './SignupPage'